### ISSUE TITLE
看了源码，对从机来说，有点冗余，尤其是接口那里，当寄存器大于一定的值之后，这个可能就不适用了

### ISSUE THREAD

**Issue by miskin-lee** [loogg/agile_modbus#11]
看了源码，对从机来说，有点冗余，尤其是接口那里，当寄存器大于一定的值之后，这个可能就不适用了

**Comment by loogg** [comment]
能具体说明下么
Util 文件夹下的是我提供的简易从机接入接口，文档里也有说明由于局部数组的原因，每一块的长度不能大于一定值

**Comment by leejean-wq** [comment]
感谢大佬百忙之中回复，您的包很好用！不过从机接口那部分，第一点就是寄存器数量不能超过一定值，所以就造成了有些多寄存器项目无法使用；第二点就是未定义到的寄存器地址，当主机进行读取操作，仍然会有返回，结果为0。

**Comment by leejean-wq** [comment]
> 能具体说明下么 Util 文件夹下的是我提供的简易从机接入接口，文档里也有说明由于局部数组的原因，每一块的长度不能大于一定值
感谢大佬百忙之中回复，您的包很好用！不过从机接口那部分，第一点就是寄存器数量不能超过一定值，所以就造成了有些多寄存器项目无法使用；第二点就是未定义到的寄存器地址，当主机进行读取操作，仍然会有返回，结果为0。

**Comment by loogg** [comment]
我文档里都有说明啊，为什么多寄存器项目无法使用，寄存器多定义几个数组成员不就行了，它是数组啊，不是单单一个成员。

至于为何是能返回且是0，这个每个人用法都不一，我是尽可能兼容，个人另外的需求的话可以去改下源码。

![image](https://user-images.githubusercontent.com/28485255/199652540-5c95af7f-59ae-42ec-a784-a4b99dc4ae71.png)

![image](https://user-images.githubusercontent.com/28485255/199652581-ff04f48b-ac5e-4b85-9305-ca67af74fc26.png)

**Comment by loogg** [comment]
![image](https://user-images.githubusercontent.com/28485255/199652790-ea923708-5d63-49fe-9708-dbc27cf5f7f0.png)

**Comment by SnowSakuraKo** [comment]
因为是数组，所以util的接口仅适用于连续的数据。如果是分开的数据还是需要自己实现，用其他数据结构进行数据的存储。 @leejean-wq
