### ISSUE TITLE
agile_modbus_receive_msg_judge检验出问题

### ISSUE THREAD

**Issue by how0723** [loogg/agile_modbus#5]
agile_modbus_receive_msg_judge是怎么回事

**Comment by loogg** [comment]
请给下详细的代码

**Comment by how0723** [comment]
master
`
void modbus_cycle_entry()
{
    uint8_t ctx_send_buf[AGILE_MODBUS_MAX_ADU_LENGTH];
    uint8_t ctx_read_buf[AGILE_MODBUS_MAX_ADU_LENGTH];
    uint16_t hold_register[10];

    agile_modbus_rtu_t ctx_rtu;
    agile_modbus_t *ctx = &ctx_rtu._ctx;
    agile_modbus_rtu_init(&ctx_rtu, ctx_send_buf, sizeof(ctx_send_buf), ctx_read_buf, sizeof(ctx_read_buf));
    agile_modbus_set_slave(ctx, 1);

    while (1)
    {
        printf("Running.\r\n");

        int send_len = agile_modbus_serialize_read_registers(ctx, 0, 10);
        rs485_send_man(ctx->send_buf, send_len);
        // printf("modbus send len=%d. data = %02x %02x %02x %02x %02x %02x %02x %02x\r\n",
        //        send_len,
        //        ctx->send_buf[0],
        //        ctx->send_buf[1],
        //        ctx->send_buf[2],
        //        ctx->send_buf[3],
        //        ctx->send_buf[4],
        //        ctx->send_buf[5],
        //        ctx->send_buf[6],
        //        ctx->send_buf[7]);
        int read_len = rs485_recv_man(ctx->read_buf, ctx->read_bufsz, 1000);
        if (read_len < 0)
        {
            printf("Receive error, now exit.\r\n");
            break;
        }

        if (read_len == 0)
        {
            printf("Receive timeout.\r\n");
            continue;
        }
        printf("read_len=%d\r\n", read_len);
        int rc = agile_modbus_deserialize_read_registers(ctx, read_len, hold_register);
        if (rc < 0)
        {
            printf("Receive failed. rc=%d\r\n", rc);
            if (rc != -1)
            {
                printf("Error code:%d\r\n", -128 - rc);
            }
            continue;
        }

        printf("Hold Registers:\r\n");
        for (int i = 0; i < 10; i++)
        {
            printf("Register [%d]: 0x%04X\r\n", i, hold_register[i]);
        }
        printf("\r\n\r\n\r\n");
    }
}

`

salve
`
#include "slave.h"
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include "rt_tick.h"

#define DBG_ENABLE
#define DBG_COLOR
#define DBG_SECTION_NAME "slave"
#define DBG_LEVEL        DBG_LOG
#include "dbg_log.h"

#define TAB_MAX_NUM 10

static pthread_mutex_t _mtx;
static uint8_t _tab_bits[TAB_MAX_NUM] = {0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static uint8_t _tab_input_bits[TAB_MAX_NUM] = {0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static uint16_t _tab_registers[TAB_MAX_NUM] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static uint16_t _tab_input_registers[TAB_MAX_NUM] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

/**
 * @brief   从机回调函数
 * @param   ctx modbus 句柄
 * @param   slave_info 从机信息体
 * @return  =0:正常;
 *          <0:异常
 *             (-AGILE_MODBUS_EXCEPTION_UNKNOW(-255): 未知异常，从机不会打包响应数据)
 *             (其他负数异常码: 从机会打包异常响应数据)
 */
int slave_callback(agile_modbus_t *ctx, struct agile_modbus_slave_info *slave_info)
{
    int function = slave_info->sft->function;
    int ret = 0;

    pthread_mutex_lock(&_mtx);

    switch (function) {
    case AGILE_MODBUS_FC_READ_COILS:
    case AGILE_MODBUS_FC_READ_DISCRETE_INPUTS: {
        int address = slave_info->address;
        int nb = slave_info->nb;
        int send_index = slave_info->send_index;
        int is_input = (function == AGILE_MODBUS_FC_READ_DISCRETE_INPUTS);

        for (int now_address = address, i = 0; now_address < address + nb; now_address++, i++) {
            if (now_address >= 0 && now_address < TAB_MAX_NUM) {
                int index = now_address - 0;
                agile_modbus_slave_io_set(ctx->send_buf + send_index, i,
                                          is_input ? _tab_input_bits[index] : _tab_bits[index]);
            }
        }
    } break;

    case AGILE_MODBUS_FC_READ_HOLDING_REGISTERS:
    case AGILE_MODBUS_FC_READ_INPUT_REGISTERS: {
        int address = slave_info->address;
        int nb = slave_info->nb;
        int send_index = slave_info->send_index;
        int is_input = (function == AGILE_MODBUS_FC_READ_INPUT_REGISTERS);

        for (int now_address = address, i = 0; now_address < address + nb; now_address++, i++) {
            if (now_address >= 0 && now_address < TAB_MAX_NUM) {
                int index = now_address - 0;
                agile_modbus_slave_register_set(ctx->send_buf + send_index, i,
                                                is_input ? _tab_input_registers[index] : _tab_registers[index]);
            }
        }
    } break;

    case AGILE_MODBUS_FC_WRITE_SINGLE_COIL:
    case AGILE_MODBUS_FC_WRITE_MULTIPLE_COILS: {
        int address = slave_info->address;

        if (function == AGILE_MODBUS_FC_WRITE_SINGLE_COIL) {
            if (address >= 0 && address < TAB_MAX_NUM) {
                int index = address - 0;
                int data = *((int *)slave_info->buf);
                _tab_bits[index] = data;
            }
        } else {
            int nb = slave_info->nb;
            for (int now_address = address, i = 0; now_address < address + nb; now_address++, i++) {
                if (now_address >= 0 && now_address < TAB_MAX_NUM) {
                    int index = now_address - 0;
                    uint8_t status = agile_modbus_slave_io_get(slave_info->buf, i);
                    _tab_bits[index] = status;
                }
            }
        }
    } break;

    case AGILE_MODBUS_FC_WRITE_SINGLE_REGISTER:
    case AGILE_MODBUS_FC_WRITE_MULTIPLE_REGISTERS: {
        int address = slave_info->address;

        if (function == AGILE_MODBUS_FC_WRITE_SINGLE_REGISTER) {
            if (address >= 0 && address < TAB_MAX_NUM) {
                int index = address - 0;
                int data = *((int *)slave_info->buf);
                _tab_registers[index] = data;
            }
        } else {
            int nb = slave_info->nb;
            for (int now_address = address, i = 0; now_address < address + nb; now_address++, i++) {
                if (now_address >= 0 && now_address < TAB_MAX_NUM) {
                    int index = now_address - 0;
                    uint16_t data = agile_modbus_slave_register_get(slave_info->buf, i);
                    _tab_registers[index] = data;
                }
            }
        }

    } break;

    case AGILE_MODBUS_FC_MASK_WRITE_REGISTER: {
        int address = slave_info->address;
        if (address >= 0 && address < TAB_MAX_NUM) {
            int index = address - 0;
            uint16_t data = _tab_registers[index];
            uint16_t and = (slave_info->buf[0] << 8) + slave_info->buf[1];
            uint16_t or = (slave_info->buf[2] << 8) + slave_info->buf[3];

            data = (data & and) | (or &(~and));

            _tab_registers[index] = data;
        }
    } break;

    case AGILE_MODBUS_FC_WRITE_AND_READ_REGISTERS: {
        int address = slave_info->address;
        int nb = (slave_info->buf[0] << 8) + slave_info->buf[1];
        uint16_t address_write = (slave_info->buf[2] << 8) + slave_info->buf[3];
        int nb_write = (slave_info->buf[4] << 8) + slave_info->buf[5];
        int send_index = slave_info->send_index;

        /* Write first. 7 is the offset of the first values to write */
        for (int now_address = address_write, i = 0; now_address < address_write + nb_write; now_address++, i++) {
            if (now_address >= 0 && now_address < TAB_MAX_NUM) {
                int index = now_address - 0;
                uint16_t data = agile_modbus_slave_register_get(slave_info->buf + 7, i);
                _tab_registers[index] = data;
            }
        }

        /* and read the data for the response */
        for (int now_address = address, i = 0; now_address < address + nb; now_address++, i++) {
            if (now_address >= 0 && now_address < TAB_MAX_NUM) {
                int index = now_address - 0;
                agile_modbus_slave_register_set(ctx->send_buf + send_index, i, _tab_registers[index]);
            }
        }
    } break;

    default:
        ret = -AGILE_MODBUS_EXCEPTION_ILLEGAL_FUNCTION;
        break;
    }

    pthread_mutex_unlock(&_mtx);

    return ret;
}

extern int rtu_slave_init(const char *dev, pthread_t *tid);
extern int tcp_slave_init(int port, pthread_t *tid);

int main(int argc, char *argv[])
{
    if (argc < 2) {
        LOG_E("Please enter ModbusSlave [dev] !");
        return -1;
    }

    pthread_mutex_init(&_mtx, NULL);

    rt_tick_init();

    pthread_t rtu_tid;
//    pthread_t tcp_tid;

    int rc1 = rtu_slave_init(argv[1], &rtu_tid);
    //int rc2 = tcp_slave_init(atoi(argv[2]), &tcp_tid);

    if (rc1 == 0)
        pthread_join(rtu_tid, NULL);

//    if (rc2 == 0)
//        pthread_join(tcp_tid, NULL);

    return 0;
}
`

**Comment by how0723** [comment]
master 发送8字节，slave回复是25字节

**Comment by loogg** [comment]
能否描述的详细些，是主机出问题呢，还是从机出问题呢。`slave 回复 25 字节` 这个 slave 是什么工具呢，回复的数据能提供下么

**Comment by how0723** [comment]
slave回复数据：01 03 14 00 00 00 01 00 02 00 03 00 04 00 05 00 06 00 07 00 08 00 09 cd 51

**Comment by how0723** [comment]
就是复现你的rtu master slave

**Comment by how0723** [comment]
不好意思，我刚发现是我的单片机接收有问题，接收的数据和发送不一样 （01 03 00 00 00 0a c5 cd 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00）

**Comment by how0723** [comment]
这是单片机接收到的数据：00 01 03 14 00 00 00 01 00 02 00 03 00 04 00 05 00 06 00 07 00 08 00 09 cd，有个错位

**Comment by how0723** [comment]
gd32f450单片机

**Comment by loogg** [comment]
你这单片机接收错了和我库有啥关系。。你多了一个 00 脏数据肯定解析不过呀，应用层要做脏数据过滤处理

**Comment by how0723** [comment]
已解决，不是脏数据，是硬件电路的问题，导致头部多了一个0x00
