### ISSUE TITLE
agile_modbus_rtu_check_integrity校验不通过

### ISSUE THREAD

**Issue by ganggangl** [loogg/agile_modbus#7]
按照库中校验函数,高位在后地位在前,agile_modbus_rtu_check_integrity中crc_received的值的算法是颠倒的
`
static int agile_modbus_rtu_check_integrity(agile_modbus_t *ctx, uint8_t *msg, const int msg_length)
{
    uint16_t crc_calculated;
    uint16_t crc_received;

    crc_calculated = agile_modbus_rtu_crc16(msg, msg_length - 2);
    crc_received = (msg[msg_length - 2] << 8) | msg[msg_length - 1];/*该处应修改为crc_received = (msg[msg_length - 1] << 8) | msg[msg_length - 2];*/

    //mrd_log_printf(MRD_DEBUG,"crc_calculated = %d,crc_received=%d\n",crc_calculated,crc_received);
    /* Check CRC of msg */
    if (crc_calculated == crc_received)
        return msg_length;

    return -1;
}
`

**Comment by loogg** [comment]
Modbus 是大端方式，高八位在前字节，低八位后字节，你自己用工具试试就知道



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: edwin ***@***.***&gt;
发送时间: 2022年5月1日 15:42
收件人: loogg/agile_modbus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [loogg/agile_modbus] agile_modbus_rtu_check_integrity校验不通过 (Issue #7)





 
按照库中校验函数,高位在后地位在前,agile_modbus_rtu_check_integrity中crc_received的值的算法是颠倒的
 `
 static int agile_modbus_rtu_check_integrity(agile_modbus_t *ctx, uint8_t *msg, const int msg_length)
 {
 uint16_t crc_calculated;
 uint16_t crc_received;
 crc_calculated = agile_modbus_rtu_crc16(msg, msg_length - 2); crc_received = (msg[msg_length - 2] << 8) | msg[msg_length - 1];/*该处应修改为crc_received = (msg[msg_length - 1] << 8) | msg[msg_length - 2];*/ //mrd_log_printf(MRD_DEBUG,"crc_calculated = %d,crc_received=%d\n",crc_calculated,crc_received); /* Check CRC of msg */ if (crc_calculated == crc_received)     return msg_length; return -1;  
}
 `

**Comment by loogg** [comment]
Poll 和 slave 工具你用着看看报文



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: edwin ***@***.***&gt;
发送时间: 2022年5月1日 15:42
收件人: loogg/agile_modbus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [loogg/agile_modbus] agile_modbus_rtu_check_integrity校验不通过 (Issue #7)





 
按照库中校验函数,高位在后地位在前,agile_modbus_rtu_check_integrity中crc_received的值的算法是颠倒的
 `
 static int agile_modbus_rtu_check_integrity(agile_modbus_t *ctx, uint8_t *msg, const int msg_length)
 {
 uint16_t crc_calculated;
 uint16_t crc_received;
 crc_calculated = agile_modbus_rtu_crc16(msg, msg_length - 2); crc_received = (msg[msg_length - 2] << 8) | msg[msg_length - 1];/*该处应修改为crc_received = (msg[msg_length - 1] << 8) | msg[msg_length - 2];*/ //mrd_log_printf(MRD_DEBUG,"crc_calculated = %d,crc_received=%d\n",crc_calculated,crc_received); /* Check CRC of msg */ if (crc_calculated == crc_received)     return msg_length; return -1;  
}
 `
